# --- Configuraci贸n de funciones ---
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["airtable"]
  included_files = ["netlify/functions/**"]
  timeout = 10

# --- Configuraci贸n de build ---
[build]
  base = ""
  command = "npm install && npm run build"
  publish = "dist"

# --- Variables de entorno para producci贸n ---
[build.environment]
  NODE_ENV = "production"
  AIRTABLE_TIMEOUT = "8000"
  NETLIFY_USE_YARN = "true"

# --- Redirecci贸n global para SPA (React/Vite) ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
