[build]
  base = "client"
  command = "npm install && npm run build"
  publish = "client/dist"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
