# --- Configuración de funciones ---
[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# --- Configuración de build ---
[build]
  command = "npm install && npm run build"
  publish = "client/dist"

# --- Redirección global para SPA (React/Vite) ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
